spring:
  application:
    name: zkl-ai-agent
  profiles:
    active: stdio
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
#      server:
#        name: webmvc-mcp-server
#        version: 1.0.0
#        type: SYNC # 同步
#        sse-message-endpoint: /mcp/message  # SSE 消息端点路径
#        sse-endpoint: /sse                  # SSE 端点路径

server:
  port: 8127
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zkl.zklaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
